apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

configMapGenerator:
- name: express-backend-map
  behavior: merge
  env: config.properties

patches:
- path: patch.yaml


namespace: default
