apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

configMapGenerator:
- name: express-backend-map
  behavior: replace
  env: config.properties

patches:
- path: patch.yaml


namespace: default
