apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-test

resources: 
- deployment.yaml
- service.yaml

configMapGenerator:
- envs:
  - config.properties
  name: express-backend-map

labels:
- includeSelectors: true
  pairs:
    app: express-backend-app